warmup_workout_data = [
    {"exercise": "EMOM 10\nOdd: Thrusters increase weight\nEven: 15 cal Row\n15 Knee Tucks Every Other Round"},
    {"exercise": "EMOM 10\nOdd: Back Squat increase weight\nEven: 15 cal row\n15 Knee Tucks Every Other Round"},
    {"exercise": "EMOM 6\n5 x Back Squat\nFor Time: 10 - 1\n10 DB Snatch Right\n10 DB Snatch Left\n10 DG Goblet Squat"},
    {"exercise": "EMOM 6\n3 Hang Squat Cleans\n8 Minute Ladder(add 2 reps per round):\n6 Cal Row\n6 Wall Balls\n"},
    {"exercise": "EMOM 10\n1. Bench Press 8, 8, 6, 6, 4\n2. Bent Over Row 8"},
    {"exercise": "EMOM 10\nBack Squat 5, 5, 4, 4, 3, 3, 2, 2, 1, 1"},
    {"exercise": "EMOM 10\nBB Bench Press 12, 10, 8, 8, 6\nBent Over Reverse Flys 12"},
    {"exercise": "EMOM 10\nDB Bench Press\n1 Hanging poer clean"},
    {"exercise": "EMOM 8\nFront Squat 4, 3, 2, 1\n3 x Box Jump\nThen:\n20 x KB Jump goblet squat"},
    {"exercise": "EMOM 12\n12 x Kneeling Shoulder Press\n8 x Heaves\n20 Sec Suitcase carry ES"},
    {"exercise": "EMOM 8\n5 x DB Bench Complex(Single, Single, Double)\n2 x Hang power clean\nThen:\nMax Press ups and Pullups"},
    {"exercise": "EMOM 10\n8 x DB Bench press\n1 x Hang power clean"},
    {"exercise": "EMOM 8\nFront squat 4, 4, 2, 2\nAt 8 mins\n3 x Box jump\n25 x Back Squat with last front squat weight"},
    {"exercise": "EMOM 8\nBB Bench press 12, 10, 8, 12\n12 x Bent Over reverse flys"},
]
